version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python app.py
    env_file:
      - ./.env
    depends_on:
      - db
    container_name: api
  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_name
    container_name: db

volumes:
  postgres_data: